name: Deploy to Heroku

on:
  workflow_dispatch:
  push:
    branches:
      - 'release'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  
        run: echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

  deploy:
    needs: docker
    name: Deploy to Heroku
    runs-on: ubunto-latest
    concurrency: deploy-group
    steps:
      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}