# fly.toml app configuration file generated for careerday on 2024-07-16T16:51:11-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'careerday'
primary_region = 'lax'

[build]
  image = 'beckwithc/careerday:latest'

[env]
  ASPNETCORE_URL="http://+:8080"
  Cloudinary__CloudName="da7nuaie7"
  Cloudinary__ApiKey="832726646735491"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256MB'
